### ISSUE TITLE
Identity provider single sign on URL and identity provider issuer usage

### ISSUE THREAD

**Issue by xmt1139057136** [oktadev/okta-spring-boot-saml-example#14] opened 2020-06-21 09:54 UTC
1.       Identity Provider Single Sign-On URL:
 
2.       Identity Provider Issuer:
 
3.       X.509 Certificate:
I’ve attached the certificate.

How to use these three?

**Comment by mraible** [comment] 2020-06-22 16:01
@xmt1139057136 If you follow the [tutorial](https://developer.okta.com/blog/2017/03/16/spring-boot-saml) for this repo, everything should work. If it doesn't work for you, please describe the steps to reproduce. I'm closing this issue due to a lack of information, but please re-open it if you have steps to reproduce any problems you're having.

**Closed as completed by mraible** 2020-06-22 16:01 UTC
